
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]


output_dir: ./output/dcea

PResNet:
  depth: 10
  freeze_at: -1
  freeze_norm: False
  pretrained: False

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  num_encoder_layers: 1
  dropout: 0.2


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100
  num_queries: 100
  dropout: 0.

RTDETRPostProcessor:
  num_top_queries: 100


optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.0001
      weight_decay: 0.
    -
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.0001
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

